### ISSUE TITLE
Cannot Build MAVS

### ISSUE THREAD

**Issue by tayabalik** [CGoodin/mavs_ros#1]
According to the documentation it asks to make a 'build' folder in the MAVS folder. Should I make a new blank directory named MAVS? or do I have to clone a repo?
Am I missing something? I followed the steps correctly to make embree.

**Comment by CGoodin** [comment]
MAVS is built separately from the mavs_avt_example repo. Follow the instructions here:

https://mavs-documentation.readthedocs.io/en/latest/#building-mavs
